/* @settings

name: Encore
id: encore-settings
settings:
  - 
    id: theme-dark
    title: Theme ‚Ä¢ Dark Mode
    description: Theme used in dark mode
    type: class-select
    allowEmpty: false
    default: encore-theme-dark
    options:
      - 
        label: Obsidian Redux
        value: encore-theme-dark
      - 
        label: Cobalt
        value: encore-theme-dark-cobalt
      - 
        label: Mercury
        value: encore-theme-dark-mercury
      - 
        label: Iron
        value: encore-theme-dark-iron
      - 
        label: Carbon
        value: encore-theme-dark-carbon
      - 
        label: Blackout
        value: encore-theme-dark-blackout
      - 
        label: Obsidian
        value: encore-theme-dark-obsidian
      - 
        label: Blue Slate
        value: encore-theme-dark-slate
      - 
        label: Atom (One Dark)
        value: encore-theme-dark-atom
      - 
        label: RGB
        value: encore-theme-dark-rgb
  -
    id: theme-light
    title: Theme ‚Ä¢ Light Mode
    description: Theme used in light mode
    type: class-select
    allowEmpty: false
    default: encore-theme-light
    options:
      - 
        label: Obsidian Redux
        value: encore-theme-light
      - 
        label: Sterling
        value: encore-theme-light-sterling
      - 
        label: Atom (One Light)
        value: encore-theme-light-atom
  -
    id: colors
    title: üé® Colors in Text
    description: All of Encore's themes come with colors for headers, bold, italics, etc... Enable them here, or choose your own
    type: class-select
    allowEmpty: false
    default: encore-colors-neutral
    options:
      - 
        label: Neutral
        value: encore-colors-neutral
      - 
        label: Colorful
        value: encore-colors-colorful
      - 
        label: Custom
        value: encore-colors-custom
  
  #########################################################
  # Custom Colours
  
  - 
    id: custom-colours
    title: üñåÔ∏è Custom Colours
    type: heading
    level: 1
    collapsed: true
  - 
    id: encore-custom-italic
    title: Italic Text
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  - 
    id: encore-custom-bold
    title: Bold Text
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'

  - 
    id: encore-custom-h1
    title: Header One
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  - 
    id: encore-custom-h2
    title: Header Two
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  - 
    id: encore-custom-h3
    title: Header Three
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  - 
    id: encore-custom-h4
    title: Header Four
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  - 
    id: encore-custom-h5
    title: Header Five
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  - 
    id: encore-custom-h6
    title: Header Six
    type: variable-themed-color
    opacity: false
    format: hex
    default-light: '#000000'
    default-dark: '#ffffff'
  
  
  #########################################################
  # Extras
  
  - 
    id: extras
    title: üíé Extras
    type: heading
    level: 1
    collapsed: true
  
  -
    id: encore-coloured-tooltip
    title: Coloured Tooltip
    description: Make tooltips stand out much more by applying your theme colour to the border
    type: class-toggle
  - 
  -
    id: encore-bright-accent
    title: Use Bright Accent Colour
    description: Enable if you're using a bright accent color that is hard to read white text on. Will change text to be black.
    type: class-toggle
  - 
    id: blur-amount
    title: Blur Amount
    description: Lowering the blur amount helps increase performance
    type: class-select
    allowEmpty: false
    default: encore-blur-full
    options:
      - 
        label: Full
        value: encore-blur-full
      - 
        label: Less
        value: encore-blur-less
      - 
        label: Off
        value: encore-blur-off

  
  
  #########################################################
  # Feature Toggles
  

  - 
    id: feature-toggles
    title: ‚öôÔ∏è Feature Toggles
    type: heading
    level: 1
    collapsed: true
  -
    id: encore-disable-fancy-headers
    title: Disable Fancy Headers
    description: Encore changes headers to overlap main content for a nice blur effect. Disable this if you see issues
    type: class-toggle
  -
    id: encore-disable-typography-spacing
    title: Disable Typography Spacing
    description: Encore adds a lot of white space to your notes to make them easier to read. Disable if you don't like how your notes now look.
    type: class-toggle
  -
    id: encore-disable-grain
    title: Disable Grainy Background
    description: Encore adds a subtle grain effect around the main workspace
    type: class-toggle
  -
    id: encore-disable-clickability-fix
    title: Disable Clickability Fix
    description: Encore makes it easier to click the edge of a document by adding some invisible padding. May cause issues if you have content that exceeds the width of your page. No effect on mobile version.
    type: class-toggle
  -
    id: encore-no-calendar
    title: Disable Calendar Integration
    description: Encore makes some changes to Calendar. Turn this on to keep the default look
    type: class-toggle
  -
    id: encore-no-excalidraw
    title: Disable Excalidraw Integration
    description: Encore makes some changes to Excalidraw to integrate it better with Obsidian. Turn this on to revert to Excalidraw's default theme
    type: class-toggle
  -
    id: encore-no-makemd
    title: Disable MAKE.md Integration
    description: Encore makes some changes to MAKE.md to enhance its look and feel. Turn this on to disable
    type: class-toggle
*/